apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-example
  namespace: argo
spec:
  entrypoint: example
  templates:
  - name: example
    dag:
      tasks:
      - name: A
        arguments:
          parameters: [{name: message,value: A}]
        templateRef:
          name: echo-template
          template: echo
      - name: B
        templateRef:
          name: echo-template
          template: echo
        arguments:
          parameters: [{name: message,value: B}]
      - name: C
        templateRef:
          name: echo-template
          template: echo
        arguments:
          parameters: [{name: message, value: C}]
      - name: D
        dependencies: [A,B]
        templateRef:
          name: echo-template
          template: echo
        arguments:
          parameters: [{name: message,value: D}]
      - name: E
        dependencies: [C,D]
        templateRef:
          name: echo-template
          template: echo
        arguments:
          parameters: [{name: message,value: E}]
      - name: F
        dependencies: [C]
        templateRef:
          name: echo-template
          template: echo
        arguments:
          parameters: [{name: message,value: F}]
      - name: G
        dependencies: [D,F]
        templateRef:
          name: echo-template
          template: echo
        arguments:
          parameters: [{name: message,value: G}]